apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: chatterbox

build:
  artifacts:
    - image: ghcr.io/rga-atl/monerochat
      docker:
        dockerfile: Dockerfile
        buildArgs:
          BUILDKIT_INLINE_CACHE: "1"
      platforms:
        - linux/arm64
    - image: ghcr.io/rga-atl/xmrchat-mining-proxy
      context: mining-proxy
      docker:
        dockerfile: Dockerfile
        buildArgs:
          BUILDKIT_INLINE_CACHE: "1"
      platforms:
        - linux/arm64

manifests:
  kustomize:
    paths:
      - kubernetes
