apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - tunnel.yaml
  - mining-proxy-deployment.yaml
  - mining-proxy-service.yaml