apiVersion: v1
kind: Service
metadata:
  name: mining-proxy
  labels:
    app: mining-proxy
spec:
  type: ClusterIP
  selector:
    app: mining-proxy
  ports:
    - name: ws
      port: 8080
      targetPort: 8080
      protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
