apiVersion: v1
kind: Service
metadata:
  name: chatterbox
  labels:
    app: chatterbox
spec:
  type: ClusterIP
  selector:
    app: chatterbox
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  sessionAffinity: ClientIP 
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
